version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Exposes backend port 3001 to host port 3001
    container_name: lightnote-backend
    environment:
      # Add any backend-specific environment variables here
      # NODE_ENV: development
      PORT: 3001
    networks:
      - lightnote-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # This VITE_API_BASE_URL is available during the 'pnpm build' in the frontend Dockerfile
        VITE_API_BASE_URL: http://backend:3001 
    ports:
      - "8080:80" # Exposes Nginx port 80 (from frontend Dockerfile) to host port 8080
    container_name: lightnote-frontend
    depends_on:
      - backend
    environment:
      # Environment variables for Nginx (if needed at runtime, though Vite bakes it in)
      # NGINX_PORT: 80 
    networks:
      - lightnote-network

networks:
  lightnote-network:
    driver: bridge

# Optional: Define named volumes if you need persistent storage (e.g., for a database)
# volumes:
#   db_data: 